### ISSUE TITLE
[bug]: Ctrl+A does not work in the Add-on text fields

### ISSUE THREAD

**Issue by McTom234** [berndgz/lnxngfmsdm#1]
Putting cursor in the text field for the Add-on configuration and pressing Ctrl+A does not select the text.

**Comment by berndgz** [comment]
Hey @McTom234 ,
[Ctrl]+[A] should work now in the text entry fields.
Please try version 1.0.1 and let me know if it solves the issue.

**Comment by McTom234** [comment]
Nice! Thank you!
